### PR TITLE
K8s docs

### PR DESCRIPTION
**Pull request by salilsub**
This is an update to the k8s docs to include include the new Gateway API support as well as migrate docs out of GitHub and into the official ngrok docs.

### CODE REVIEW

**Comment by russorat** [comment]
```
  - On source page path = /docs/k8s/:
     -> linking to ./user-guide/ingress-to-edge-relationship/ (resolved as: /docs/k8s/user-guide/ingress-to-edge-relationship/)
     -> linking to ./deployment-guide/README/ (resolved as: /docs/k8s/deployment-guide/README/)
     -> linking to ./user-guide/README/ (resolved as: /docs/k8s/user-guide/README/)
  
  - On source page path = /docs/k8s/developer-guide/architecture/:
     -> linking to ../../internal/controllers/ippolicy_controller.go/ (resolved as: /docs/k8s/internal/controllers/ippolicy_controller.go/)
     -> linking to ../../internal/controllers/domain_controller.go/ (resolved as: /docs/k8s/internal/controllers/domain_controller.go/)
     -> linking to ../../internal/controllers/httpsedge_controller.go/ (resolved as: /docs/k8s/internal/controllers/httpsedge_controller.go/)
     -> linking to ../../internal/controllers/tcpedge_controller.go/ (resolved as: /docs/k8s/internal/controllers/tcpedge_controller.go/)
  
  - On source page path = /docs/k8s/developer-guide/releasing/:
     -> linking to ../helm/ingress-controller/README/ (resolved as: /docs/k8s/developer-guide/helm/ingress-controller/README/)
  
  - On source page path = /docs/k8s/examples/:
     -> linking to ./hello-world/README/ (resolved as: /docs/k8s/examples/hello-world/README/)
     -> linking to ./consul/README/ (resolved as: /docs/k8s/examples/consul/README/)
     -> linking to ./external-dns/README/ (resolved as: /docs/k8s/examples/external-dns/README/)
     -> linking to ./oauth/README/ (resolved as: /docs/k8s/examples/oauth/README/)
```

**Comment by salilsub** [comment]
Open updates
- [ ] Combine the "How it works" and "Connecting to edges" page into a single "Ingress Controller Page"
- [ ] Create an equivalent page for the Gateway API
- [ ] Verify all examples and links are correct

**Review by Abdiramen — APPROVED** [review]
looks good to me

**Comment by russorat** [comment]
I think this is missing at least the following:
- CRD definitions
- annotations reference page

Also, there are a lot of files in here that aren't linked to or available in the navigation.

**Review by russorat — APPROVED** [review]
it's a good start. let's follow up immediately after with updates.

**Comment by salilsub** [comment]
We're going to merge these docs based on these changes so we have something people can use to start testing out the Gateway API. However, there should be additional work to make these pages easier to digest.

**Pull request merged**
