### PR TITLE
ngrok-agent: changelog for v3.2.2

### PR DESCRIPTION
**Pull request by natasha-jarus**
This is a bugfix release; not much to say but it sure is worth shipping

### CODE REVIEW

**Comment by russorat** [comment]
this one has to wait for 3.3 i'm guessing? https://github.com/ngrok-private/ngrok/pull/16327

**Comment by natasha-jarus** [comment]
correct; we can roll them both up into a 3.3.0 release if you want

**Review by russorat — APPROVED** [review]
lgtm

**Comment by natasha-jarus** [comment]
are we cutting two releases?

**Comment by russorat** [comment]
no, we can wait for additional fixes for a minor release

**Comment by russorat** [comment]
sorry, i realize my last message was vague. 

Let's release this patch version now and we will wait to release the next minor version at a future date.

**Pull request merged**
