### PR TITLE
Agent 3.1.1 Changelog

### PR DESCRIPTION
**Pull request by thebluetiger**

### CODE REVIEW

**Review by krwenholz — APPROVED** [review]
LGTM! Level of detail on `web_allow_hosts` might need tuning, but I'm not sure what else to suggest.

**Comment by bobzilladev** [comment]
Added PR for agent doc change: https://github.com/ngrok/ngrok-docs/pull/151

**Comment by krwenholz** [comment]
That looks great guys! Thank you.

**Review by russorat — APPROVED** [review]
lgtm

**Pull request merged**
