### PR TITLE
Add additional rules to Traffic Policy gallery

### PR DESCRIPTION
**Pull request by joelhans**
I got a request from Zubin to add the rules I created for this [recent article](https://ngrok.com/blog-post/api-gateway-policy-management-examples) directly into the existing rule gallery. 

I also added a quick mention and link to said article, as it provides a bit more helpful context and a demo deployment for anyone who wants to try these configs out in a local development environment.

### CODE REVIEW

**Comment by russorat** [comment]
if you can resolve the conflicts, i will review and approve

**Comment by joelhans** [comment]
Thanks @russorat! Looks like I cleared out the merge conflicts without breaking anything.

**Review by russorat — APPROVED** [review]
lgtm!

**Comment by russorat** [comment]
looks like there are still some conflicts somewhere. let me take a look at your branch

**Comment by russorat** [comment]
alright, i think i fixed this

**Pull request merged**
