### PR TITLE
changelog for agent release 3.5.0

### PR DESCRIPTION
**Pull request by bobzilladev**

### CODE REVIEW

**Comment by salilsub** [comment]
Do we state anywhere what the valid options are for app-protocol? If it's in the `--help` command that's sufficient.

**Comment by bobzilladev** [comment]
> Do we state anywhere what the valid options are for app-protocol? If it's in the `--help` command that's sufficient.

Not currently: `--app-protocol string              Set application protocol`

It doesn't do local validation since we want that to be an error from the server side so we don't have to constantly update it. But since this feature isn't totally launched yet this is a bit vague.

**Comment by salilsub** [comment]
I agree that we should not validate locally but I do think we should state somewhere what the accepted values are. More so that a user knows what the right values are rather than validating whether what they enter is correct.

**Comment by bobzilladev** [comment]
Added a note about the `--app-protocol` value.

**Review by salilsub — APPROVED** [review]

**Pull request merged**
